services:
  - type: web
    name: travel-planner-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PGHOST
        sync: false
      - key: PGPORT
        sync: false
      - key: PGDATABASE
        sync: false
      - key: PGUSER
        sync: false
      - key: PGPASSWORD
        sync: false
      - key: ACCESS_TOKEN_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: PEXELS_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false